# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{browser_detector}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)", "Kelley Reynolds"]
  s.date = %q{2009-10-19}
  s.description = %q{Determines the name and version of the browser currently making a request.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "browser_detector.gemspec",
     "lib/browser_detector.rb",
     "lib/browser_detector/detector.rb",
     "lib/browser_detector/rails.rb",
     "lib/browser_detector/rails/view_helpers.rb",
     "test/browser_detector/detector_test.rb",
     "test/browser_detector/rails/view_helpers_test.rb",
     "test/browser_detector_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/midas/browser_detector}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Determines the name and version of the browser currently making a request.}
  s.test_files = [
    "test/browser_detector/detector_test.rb",
     "test/browser_detector/rails/view_helpers_test.rb",
     "test/browser_detector_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
    else
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
  end
end
